# Generated by Django 4.0.5 on 2022-07-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=1000)),
                ('directions', models.CharField(max_length=1000)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
